### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [loociano/tamagotch#1]
The site is inaccessible over IPv6.

While Github Pages officially doesn't support IPv6 for custom domains, it can be easily worked around by adding 2a04:4e42::403 as the AAAA record.

**Comment by loociano** [comment]
Hi Raul, thanks for the heads up! Done.

**Comment by tambry** [comment]
You seem to have quite a few more GitHub Pages-based sites that could use IPv6 support (can be added in exactly the same way):

* n-gage.org
* loociano.com
* esboy.org

**Comment by loociano** [comment]
Thanks! Fixed them too. 👍
